# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Swifty Profiles' do
	pod 'SwiftHTTP'
	pod 'JSONJoy-Swift'


end

target 'Swifty ProfilesTests' do

end

target 'Swifty ProfilesUITests' do

end

